modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="progressionplus"
version="1.0.0"
displayName="Progression Plus"
credits=""
displayURL=""
authors="GroupTwoSoftworks"
description="Re-imagines the vanilla minecraft progression system."

[[dependencies.progressionplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




