modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="steelpack"
version="1.0.0"
displayName="Steel"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="GroupTwoSoftworks, MCreator"
description="Adds Steel"

[[dependencies.steelpack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




