name: Build the project with github actions
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  build-pr-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code for PR
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

    - name: Run Gradle tasks
      uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
      with:
        arguments: build --no-daemon

    - name: Create Artifacts directory
      run: mkdir artifacts

    - name: Add Artifacts
      run: cp build/libs/*.jar artifacts/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: generated artifacts
        path: downloads
    

